commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("createlisting", views.createlisting, name="createlisting"),
    path("listingpage/<int:listing_id>", views.listingpage, name="listingpage"),
    path("addwatchlist/<int:listing_id>", views.addwatchlist, name="addwatchlist"),
    path("removewatchlist/<int:listing_id>", views.removewatchlist, name="removewatchlist"),
    path("placebid/<int:listing_id>", views.placebid, name="placebid"),
    path("closeauction/<int:listing_id>", views.closeauction, name="closeauction") 
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):

    pass

class Listing(models.Model):

    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64)
    description = models.CharField(max_length=120)
    urllink = models.URLField(blank=True)

    # remove bid
    # bid = models.IntegerField(max_digits=5) 
    # This user is for watchlist
    users = models.ManyToManyField(User, blank=True, related_name="listings")
    createdby = models.ForeignKey(User, on_delete=models.CASCADE, related_name="creator", default=0)

    pass

class Bids(models.Model):
    
    id = models.AutoField(primary_key = True)
    bid = models.IntegerField()
    starting_bid = models.IntegerField(default=0)
    bid_listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    biduser = models.IntegerField()
    status = models.BooleanField(default=False)

    # pass

# class Comments(models.Model):
    # pass

# class Watchlist(models.Model):

    # watchlist_userid = models.ForeignKey(User, on_delete=models.CASCADE)
    # listing = models.ForeignKey(Listing, on_delete=models.CASCADE)

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.decorators import login_required



from .models import User, Listing, Bids


def index(request):
    return render(request, "auctions/index.html", {
        "activelisting": Listing.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            # user.user_id = userid
            # user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

@login_required(login_url='login')
def createlisting(request):

    if request.method == "POST":

        # accessing & storing itemname, description & url
        new_listing = Listing()
        new_listing.title = request.POST["title"]
        new_listing.description = request.POST["description"]

        # new_listing.bid =request.POST["startingbid"]
        user_id = request.user.id
        user = User.objects.get(id=user_id)
        new_listing.createdby = user

        if request.POST["urllink"] is not None:
            new_listing.urllink = request.POST.get("urllink", "")

        new_listing.save()

        # accessing and storing bid, bid listing, bid by user and bid status
        new_bid = Bids()
        new_bid.bid = request.POST["startingbid"]
        new_bid.starting_bid = request.POST["startingbid"]
        new_bid.biduser = user.id
        new_bid.status = True

        #connect new bid foreign key to id of listing
        new_bid.bid_listing = new_listing
        new_bid.save()
                  
        
        # reverse not working
        return HttpResponseRedirect(reverse("auctions:index"))

    else:
        return render(request, "auctions/createlisting.html")

@login_required(login_url='login')
def listingpage(request, listing_id):        

    # get listing details
    current_listing = Listing.objects.get(id=listing_id)
    user_id = request.user.id

    #get bidding details. pk will be same as listing id
    listing_bid = Bids.objects.get(bid_listing=current_listing)

    # check if assosciated user id matchs with listing id
    
    watchlist_exists = current_listing.users.filter(id=user_id).exists()

    #check if logged in user is the creator of the listing

    if user_id is current_listing.createdby.id:
        iscreator = True
    else:
        iscreator = False

 
    return render(request, "auctions/listingpage.html", {
        "listing": current_listing,
        'user_id': user_id,
        "watchlist_exists": watchlist_exists,
        "bid": listing_bid,
        "iscreator": iscreator
    })

@login_required(login_url='login')
def addwatchlist(request, listing_id):

    if request.method == "POST":

        # accessing the listing
        listing = Listing.objects.get(pk=listing_id)

        # accessing the user
        # user_id = int(request.GET.get('arg1'))

        user_id = int(request.POST.get('user_id'))

        # finding the user assosciated with id

        user = User.objects.get(pk=user_id)

        # adding listing to user
        user.listings.add(listing)

        # Redirect User
        return HttpResponse("added to watch list wit user_ id" + str(user_id))

    else:
        return HttpResponse("not added")

@login_required(login_url='login')
def removewatchlist(request, listing_id):

    if request.method == "POST":

        # accessing the listing
        listing = Listing.objects.get(pk=listing_id)

        # accessing the user
        # user_id = int(request.GET.get('arg1'))

        user_id = int(request.POST.get('user_id'))

        # finding the user assosciated with id
        user = User.objects.get(pk=user_id)

        # remove listing from user
        user.listings.remove(listing)

        # Redirect User
        return HttpResponse("removed listing from watch list")

    else:
        return HttpResponse("failed to remove")    


@login_required(login_url='login')
def placebid(request, listing_id):

     # Update the existing bid assosciated with the listing

    if request.method == "POST":

        # accessing the listing
        listing = Listing.objects.get(pk=listing_id)

        #accessing the bid (bid id is the same as the listing id as they are created together)
        bid = Bids.objects.get(pk=listing_id)

        # accessing the user id that submitted the bid
        user_id = int(request.POST.get('user_id'))

        # accessing the bid
        placed_bid = int(request.POST.get('bid'))

        #Updating bid
        #check if bid is higher than current bid, status if false
        if bid.bid >= placed_bid or bid.starting_bid > placed_bid:
            return HttpResponse("Placed bid must be greater than existing bid")
        else:
            bid.bid = placed_bid
            bid.biduser = user_id

            bid.save()

        return HttpResponseRedirect(reverse("auctions:index"))

    else:
        HttpResponse("Bid adding error")

@login_required(login_url='login')
def closeauction(request, listing_id):

    if request.method == "POST":

        # access listing
        current_listing = Listing.objects.get(id=listing_id)

        # access bid
        listing_bid = Bids.objects.get(bid_listing=current_listing)

        # change bid status
        listing_bid.status = False
        listing_bid.save

        #return HttpResponse("auction closed and bid status is now" + str(listing_bid.status))

        return HttpResponseRedirect(reverse("auctions:index"))

    
        

commerce/auctions/templates/auctions/createlisting.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create Listings</h2>
    <div>
        <form action="{% url 'auctions:createlisting' %}"" method="post">
            {% csrf_token %}
            <ul>
                <li>    
                    <label for="title">Title:</label>
                    <input type="text", name="title", placeholder="Enter title">
                </li>
                <br>
                <li>
                    <label for="description">Description:</label>
                    <br>
                    <textarea name="description", placeholder="Enter Description", rows="4", cols="50"></textarea>
                </li>
                <br>
                <li>
                    <label for="urllink">URL LINK:</label>
                    <input type="url" name="urllink">                        
                </li>
                <br>
                <li>
                    <label for="startingbid">Starting Bid:</label>
                    <input type="number" required name="startingbid" placeholder="Enter Price">
                </li>
            <input type="submit" value="Create">
            </ul>
        </form>
    </div>

{% endblock %}

commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <div>
        <ul>
        {% for listing in activelisting %}
            <li>ID | {{ listing.id }} | title | {{ listing.title }} | Des | {{ listing.description }} | URL | {{ listing.urllink }} | bid | {{ listing.bid }}</li>
            <li><a href="{% url 'auctions:listingpage' listing.id %}">{{ listing.title }}</a></li>
        {% endfor %}
        </ul>
    </div>
    
{% endblock %}

commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
                <a class="nav-link" href="{% url 'auctions:createlisting' %}">Create Listing</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

commerce/auctions/templates/auctions/listingpage.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Listings Details</h2>
<div>
    <h2>Details</h2>
    <ul>
        <li>Id | {{ listing.id }}</li>
        <li>Title | {{ listing.title }}
        <li>
        <li>Des | {{ listing.description }} </li>
        <li>URL | {{ listing.urllink }}</li>
        <li>USER ID {{ user_id }}</li>
        <li>Bid Status is {{ bid.status }}</li>
        <li>Starting Bid is {{ bid.bid }}</li>
    </ul>
</div>
<div>
    {% if not watchlist_exists %}
    <form action="{% url 'auctions:addwatchlist' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="user_id" value="{{ user_id }}">
        <button type="submit">Add to watch list</button>
    </form>
    {% else %}
    <p>Remove from watch list</p>
    <form action="{% url 'auctions:removewatchlist' listing.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="user_id" value="{{ user_id }}">
        <button type="submit">Remove From Watchlist</button>
    </form>
    {% endif %}
</div>
<div>
    {% if bid.status %}
    <br>
    <h2>Place Bid</h2>
    <div>
        <form action="{% url 'auctions:placebid' listing.id %}" method="post">
            {% csrf_token %}
            <lable for="bid">Place Bid</lable>
            <input type="hidden" name="user_id" value="{{ user_id }}">
            <input type="number" id="bid" name="bid">
            <input type="submit" value="Submit">
        </form>
    </div>
    {% else %}
    <br>
    <h2>Can't place bid. Auction Closed</h2>
    {% endif %}
    <div>
        {% if iscreator %}
        <h2>Is creator. Close Auction</h2>
        <div>
            <form action="{% url 'auctions:closeauction' listing.id %}" method="POST">
                {% csrf_token %}
                <label>Close the auction</label>
                <input type="submit" value="Close">
            </form>
        </div>

        {% else %}
        <h2>Is not Creator {{ listing.createdby.id }}</h2>
        {% endif %}
    </div>
</div>

{% endblock %}

commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}